//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Md.Tga.CreateGameMailSubscriber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameTerminatedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameTerminatedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Md.Tga.CreateGameMailSubscriber.GameTerminatedText", typeof(GameTerminatedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; initial-scale=&quot;1&quot;&gt;
        ///        &lt;meta name=&quot;google&quot; content=&quot;notranslate&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;h1&gt;Hej zusammen!&lt;/h1&gt;
        ///        &lt;p&gt;Am Runden Tisch wurde das Spiel {0} beendet: {1} zum Sieger erklärt!&lt;/p&gt;
        ///        &lt;h1&gt;Spielstatistik&lt;/h1&gt;
        ///        &lt;p&gt;Ein paar Statistiken zu den bisheringen Spielen, kannst du &lt;a href=&apos;{3}&apos;&gt;hier&lt;/a&gt; einsehen.&lt;/p&gt;
        ///        &lt;p&gt;Viele Gr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyHtml {
            get {
                return ResourceManager.GetString("BodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej zusammen!
        ///
        ///Am Runden Tisch wurde das Spiel {0} beendet: {1} zum Sieger erklärt!
        ///
        ///Ein paar Statistiken zu den bisheringen Spielen, kannst du hier einsehen:
        ///
        ///{3}
        /// 
        ///Viele Grüße,
        ///
        ///{2}.
        /// </summary>
        public static string BodyText {
            get {
                return ResourceManager.GetString("BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a Winner!.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
    }
}
