sequenceDiagram
    participant C as Client
    participant InitGameSeries as InitializeGameSeriesSubscriber<br>.net core
    participant PS as Google Cloud<br>Pub/Sub
    participant SaveGameSeries as SaveGameSeriesSubscriber<br>.net core
    participant F as Google Cloud<br>Firestore
    participant SaveGame as SaveGameSubscriber<br>.net core
    participant StartGame as StartGameSubscriber<br>.net core
    participant InitSurvey as InitializeSurveySubscriber<br>.net core
    C--)+PS: INITIALIZE_GAME_SERIES
    PS--)InitGameSeries: INITIALIZE_GAME_SERIES
    deactivate PS
    activate InitGameSeries
    InitGameSeries--)+PS: SAVE_GAME_SERIES
    PS--)+SaveGameSeries: SAVE_GAME_SERIES
    deactivate PS
    SaveGameSeries->>+F: save game series
    F-->>SaveGameSeries: response
    deactivate F    
    deactivate SaveGameSeries
    InitGameSeries--)PS: START_GAME
    deactivate InitGameSeries
    activate PS
    PS--)StartGame: START_GAME
    deactivate PS
    activate StartGame
    StartGame--)+PS: SAVE_GAME
    PS--)+SaveGame: SAVE_GAME
    deactivate PS
    SaveGame->>+F: save game
    F-->>SaveGame: response
    deactivate F
    deactivate SaveGame
    StartGame--)PS: INITIALIZE_SURVEY
    deactivate StartGame
    activate PS
    PS--)InitSurvey: INTIALIZE_SURVEY
    deactivate PS
    activate InitSurvey
    Note right of InitSurvey: see surveys repository
    deactivate InitSurvey
