sequenceDiagram
    autonumber
    participant C as Client
    participant PS as Google Cloud<br>Pub/Sub
    participant SGSS as SaveGameSeriesSubscriber<br>.net core
    participant FS as Google Cloud<br>Firestore
    participant SGS as StartGameSubscriber<br>.net core
    C->>+PS: SAVE_GAME_SERIES
    PS-->>C: response
    PS--)SGSS: SAVE_GAME_SERIES
    deactivate PS
    activate SGSS
    SGSS->>+FS: save game series
    FS-->>SGSS: response
    deactivate FS
    SGSS->>+PS: START_GAME
    PS-->> SGSS: response
    deactivate SGSS
    PS--)SGS: START_GAME
    deactivate PS