sequenceDiagram
    autonumber
    participant PS as Google Cloud<br>Pub/Sub
    participant StartGS as Md.Tga.StartGameSubscriber<br>.net core
    participant FS as Google Cloud<br>Firestore
    participant SaveGS as Md.Tga.SaveGameSubscriber<br>.net core
    %% START
    PS--)+StartGS: START_GAME
    StartGS->>+FS: read game series
    FS-->>StartGS: response
    deactivate FS
    StartGS->>+FS: read number of game
    FS-->>StartGS: response
    deactivate FS
    StartGS->>+FS: read name of game
    FS-->>StartGS: response
    deactivate FS
    %% SAVE
    StartGS--)PS: SAVE_GAME
    deactivate StartGS
    activate PS
    PS--)SaveGS: SAVE_GAME
    deactivate PS
    activate SaveGS
    SaveGS->>+FS: save game
    FS-->>SaveGS: response
    deactivate FS
    SaveGS--)+PS: START_SURVEY
    deactivate SaveGS
