name: IamServiceAccounts
on:
  workflow_dispatch:
jobs:
  SerciceAccountTestReadonly:
    uses: MichaelDiers/shared-workflows/.github/workflows/iam-service-account.yaml@main
    secrets:
      gcpCredentials: ${{ secrets.GLOBAL_DEPLOY_SERVICE_ACCOUNT_JSON_TEST }}
      projectId: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      serviceAccountName: ${{ secrets.GLOBAL_FUNCTIONS_SERVICE_ACCOUNT_READONLY_TEST }}
      roleName: CustomReadonlyFirebaseAndPubSub