name: Md.Tga.TesterClient.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.TesterClient/**'
      - '.github/workflows/Md.Tga.TesterClient.yaml'
  workflow_dispatch:
env:
  APP_SETTINGS_JSON: 'backend/Md.Tga.TesterClient/Md.Tga.TesterClient/appsettings.json'
  DOCUMENT_ID: ${{ secrets.GLOBAL_COLLECTION_GAME_SERIES_TEST_CASE }}  
  PUB_SUB_TOPIC: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}
  NUGET_USERNAME: MichaelDiers
  NUGET_CONFIG: '.github/workflows/Generic-Nuget.config'
  CSPROJ_NUGET: 'backend/Md.Tga.TesterClient/Md.Tga.TesterClient/nuget.config'  
  CSPROJ_TEST_NUGET: 'backend/Md.Tga.TesterClient/Md.Tga.TesterClient.Tests/nuget.config'
  SLN_FILE: backend/Md.Tga.TesterClient/Md.Tga.TesterClient.sln
  CONFIG: Release
  FUNCTION_NAME: TesterClient
  SOURCE_DIR: 'backend/Md.Tga.TesterClient/Md.Tga.TesterClient'
  ENTRY_POINT: Md.Tga.TesterClient.Function
jobs:
  test:
    runs-on: ubuntu-latest    
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      ENVIRONMENT: 'Test'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          DocumentId: ${{ env.DOCUMENT_ID }}
          ProjectId: ${{ env.PROJECT_ID }}
          PubSubTopic: ${{ env.PUB_SUB_TOPIC }}
          Environment: ${{ env.ENVIRONMENT }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
  stage:
    needs: test
    runs-on: ubuntu-latest    
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      ENVIRONMENT: 'Stage'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          Environment: ${{ env.ENVIRONMENT }}
          DocumentId: ${{ env.DOCUMENT_ID }}
          ProjectId: ${{ env.PROJECT_ID }}
          PubSubTopic: ${{ env.PUB_SUB_TOPIC }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
  prod:
    needs: stage
    runs-on: ubuntu-latest
    environment:
      name: Md.Tga.TesterClient-Prod
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      ENVIRONMENT: 'Prod'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          Environment: ${{ env.ENVIRONMENT }}
          DocumentId: ${{ env.DOCUMENT_ID }}
          ProjectId: ${{ env.PROJECT_ID }}
          PubSubTopic: ${{ env.PUB_SUB_TOPIC }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}