name: Md.Tga.TesterClient
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.TesterClient/**'
  workflow_dispatch:
  workflow_run:
    workflows: [GoLive]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: TesterClient 
      projectName: Md.Tga.TesterClient
      solutionFolder: backend/Md.Tga.TesterClient
      trigger: http
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"StartGameSeriesTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_SERIES }}\",\"SaveSurveyResultTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_RESULT }}\",\"StartGameTerminationTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_TERMINATION }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"StartGameSeriesTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_SERIES }}\",\"SaveSurveyResultTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_RESULT }}\",\"StartGameTerminationTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_TERMINATION }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"StartGameSeriesTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_SERIES }}\",\"SaveSurveyResultTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_RESULT }}\",\"StartGameTerminationTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_TERMINATION }}\"\}'
