name: nugets/Md.Tga.Common.PubSub.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'nugets/Md.Tga.Common.PubSub/**'
  workflow_dispatch:
jobs:
  buildAndPublishNuget:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Md.Tga.Common.PubSub
      solutionFolder: nugets/Md.Tga.Common.PubSub
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
