name: Md.Tga.StartSurveySubscriber
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.StartSurveySubscriber/**'
    workflow_dispatch:
    workflow_run:
      workflows: [StartSurveySchema]
      types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: StartSurveySubscriber 
      projectName: Md.Tga.StartSurveySubscriber
      solutionFolder: backend/Md.Tga.StartSurveySubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_START_SURVEY }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY }}\"\}'

