name: BE/Md.Tga.SurveyClosedSubscriber.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.SurveyClosedSubscriber/**'
      - '.github/workflows/Md.Tga.SurveyClosedSubscriber.yaml'
      - '.github/workflows/Md.Tga.SurveyClosedSubscriber.Shared.yaml'
  workflow_dispatch:
env:
  CONFIG: Release
  FUNCTION_NAME: SurveyClosedSubscriber
  NUGET_CONFIG: '.github/workflows/Generic-Nuget.config'
  NUGET_USERNAME: MichaelDiers
  PROJECT_NAME: Md.Tga.SurveyClosedSubscriber
  SOLUTION_FOLDER: backend/Md.Tga.SurveyClosedSubscriber
  SUB_TOPIC_NAME: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}
jobs:
  Test:
    uses: ./.github/workflows/Md.Tga.SurveyClosedSubscriber.Shared.yaml
    with:
      config: Release
      environmentName: Test
      functionName: SurveyClosedSubscriber 
      nugetConfig: .github/workflows/Generic-Nuget.config
      nugetUserName: MichaelDiers
      projectName: Md.Tga.SurveyClosedSubscriber
      solutionFolder: backend/Md.Tga.SurveyClosedSubscriber
      appSettingsJson: "\\{\\"Logging\\":\\{\\"LogLevel\\":\\{\\"Microsoft\\":\\"Error\\"\\}\\},\\"ProjectId\\":\\"surveys-services-test\\",\\"Environment\\":\\"Test\\"\\}"
    secrets:
      gcpCredentials: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      projectId: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}
