name: Md.Tga.CreateGameMailSubscriber
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.CreateGameMailSubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [CreateGameMailSchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: CreateGameMailSubscriber 
      projectName: Md.Tga.CreateGameMailSubscriber
      solutionFolder: backend/Md.Tga.CreateGameMailSubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SEND_MAIL }}\",\"TerminateLinkFormat\": \"${{ secrets.GLOBAL_TERMINATE_LINK_TEST }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SEND_MAIL }}\",\"TerminateLinkFormat\": \"${{ secrets.GLOBAL_TERMINATE_LINK_STAGE }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\"\,\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SEND_MAIL }}\",\"TerminateLinkFormat\": \"${{ secrets.GLOBAL_TERMINATE_LINK_PROD }}\"\}'
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_GAME_MAIL }}