name: Md.Tga.SurveyClosedSubscriber
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.SurveyClosedSubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [SurveyClosedSchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: SurveyClosedSubscriber 
      projectName: Md.Tga.SurveyClosedSubscriber
      solutionFolder: backend/Md.Tga.SurveyClosedSubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"TopicName\":\"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_PLAYER_MAPPINGS }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"TopicName\":\"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_PLAYER_MAPPINGS }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"TopicName\":\"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_PLAYER_MAPPINGS }}\"\}'

