name: Md.Tga.SaveGameStatusSubscriber
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.SaveGameStatusSubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [SaveGameStatusSchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: SaveGameStatusSubscriber 
      projectName: Md.Tga.SaveGameStatusSubscriber
      solutionFolder: backend/Md.Tga.SaveGameStatusSubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"CreateGameMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_GAME_MAIL }}\",\"StartGameTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"CreateGameMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_GAME_MAIL }}\",\"StartGameTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\"\,\"CreateGameMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_GAME_MAIL }}\",\"StartGameTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME }}\"\}'
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_STATUS }}