name: Md.Tga.TesterClient.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.TesterClient/**'
      - '.github/workflows/Md.Tga.TesterClient.yaml'
  workflow_dispatch:
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: TesterClient 
      projectName: Md.Tga.TesterClient
      solutionFolder: backend/Md.Tga.TesterClient
      trigger: http
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"DocumentId\": \"${{ secrets.GLOBAL_COLLECTION_GAME_SERIES_TEST_CASE }}\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"DocumentId\": \"${{ secrets.GLOBAL_COLLECTION_GAME_SERIES_TEST_CASE }}\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"DocumentId\": \"${{ secrets.GLOBAL_COLLECTION_GAME_SERIES_TEST_CASE }}\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
