name: BE/Md.Tga.StartGameSubscriber.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.StartGameSubscriber/**'
      - '.github/workflows/Md.Tga.StartGameSubscriber.yaml'
  workflow_dispatch:
env:
  APP_SETTINGS_JSON: 'backend/Md.Tga.StartGameSubscriber/Md.Tga.StartGameSubscriber/appsettings.json'
  CONFIG: Release
  SOURCE_DIR: 'backend/Md.Tga.StartGameSubscriber/Md.Tga.StartGameSubscriber'
  ENTRY_POINT: Md.Tga.StartGameSubscriber.Function
  FUNCTION_NAME: StartGameSubscriber
  SLN_FILE: 'backend/Md.Tga.StartGameSubscriber/Md.Tga.StartGameSubscriber.sln'
  TOPIC_NAME_SUB: ${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME }}  
  NUGET_USERNAME: MichaelDiers
  NUGET_CONFIG: '.github/workflows/Generic-Nuget.config'
  CSPROJ_NUGET: 'backend/Md.Tga.StartGameSubscriber/Md.Tga.StartGameSubscriber/nuget.config'
  CSPROJ_TEST_NUGET: 'backend/Md.Tga.StartGameSubscriber/Md.Tga.StartGameSubscriber.Tests/nuget.config'
  COLLECTION_NAME_GAME_SERIES: ${{ secrets.GLOBAL_COLLECTION_GAME_SERIES }}
  COLLECTION_NAME_GAMES: ${{ secrets.GLOBAL_COLLECTION_GAMES }}   
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          Games.ProjectId: ${{ env.PROJECT_ID }}
          Games.CollectionName: ${{ env.COLLECTION_NAME_GAMES }}
          GameSeries.ProjectId: ${{ env.PROJECT_ID }}
          GameSeries.CollectionName: ${{ env.COLLECTION_NAME_GAME_SERIES }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ env.PROJECT_ID }}/topics/${{ env.TOPIC_NAME_SUB }}
  stage:
    needs: test
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          Games.ProjectId: ${{ env.PROJECT_ID }}
          Games.CollectionName: ${{ env.COLLECTION_NAME_GAMES }}
          GameSeries.ProjectId: ${{ env.PROJECT_ID }}
          GameSeries.CollectionName: ${{ env.COLLECTION_NAME_GAME_SERIES }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3          
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ env.PROJECT_ID }}/topics/${{ env.TOPIC_NAME_SUB }}
  prod:
    needs: stage
    runs-on: ubuntu-latest
    environment:
      name: Md.Tga.StartGameSubscriber-Prod
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:
          Games.ProjectId: ${{ env.PROJECT_ID }}
          Games.CollectionName: ${{ env.COLLECTION_NAME_GAMES }}
          GameSeries.ProjectId: ${{ env.PROJECT_ID }}
          GameSeries.CollectionName: ${{ env.COLLECTION_NAME_GAME_SERIES }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: nuget config
        run: |
          echo $(sed -e "s/\${USERNAME}/${{ env.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" ${{ env.NUGET_CONFIG }}) > ${{ env.CSPROJ_NUGET }}
          cp ${{ env.CSPROJ_NUGET }} ${{ env.CSPROJ_TEST_NUGET }}
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3          
          project_id: ${{ env.PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ env.PROJECT_ID }}/topics/${{ env.TOPIC_NAME_SUB }}
