name: Md.Tga.StartGameSeriesSubscriber
on:
  push:
    branches:
      - main
    paths:
      - 'backend/Md.Tga.StartGameSeriesSubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [StartGameSeriesSchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: StartGameSeriesSubscriber 
      projectName: Md.Tga.StartGameSeriesSubscriber
      solutionFolder: backend/Md.Tga.StartGameSeriesSubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"TopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_GAME_SERIES }}\"\}'
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_START_GAME_SERIES }}
