name: TgaSpa
on:
  push:
    branches:
      - main
    paths:
      - frontend/TgaSpa/**
      - .github/workflows/TgaSpa.yaml
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment: tga-firebase-hosting-test
    env:
      WORKING_DIRECTORY: frontend/TgaSpa 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run ci
        run: npm run ci
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.SERVICE_ACCOUNT }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          expires: 7d
          projectId: "${{ secrets.PROJECT_ID }}"
          channelId: preview
          target: tga
          entryPoint: frontend/TgaSpa 
